# Generated by Django 5.2.8 on 2025-12-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_autor_bibliografia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': (('ver_prestamos', 'Puede ver prestamos'), ('gestionar_prestamos', 'Puede gestionar prestamos'))},
        ),
        migrations.RenameField(
            model_name='multa',
            old_name='pagada',
            new_name='pagado',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='fecha_max',
            new_name='fecha_maxima',
        ),
    ]
